package report;

/**
 * Generates a formatted security report based on the results of
 * the authentication log analysis.
 *
 * <p>
 * This class is responsible for displaying security statistics,
 * threat summaries, login activity, and the overall risk assessment
 * generated by the CyberShield Security Log Analyzer.
 * </p>
 *
 * @author Prasoon Kashyap
 * @version 1.0
 */
public class ReportGenerator {

    /**
     * Generates and displays the CyberShield Security Report.
     *
     * @param totalLogs Total number of log entries processed.
     * @param successfulLogins Total number of successful login attempts.
     * @param failedLogins Total number of failed login attempts.
     * @param uniqueUsers Number of unique users found in the log file.
     * @param uniqueIPs Number of unique IP addresses found in the log file.
     * @param suspiciousUsers Number of users flagged as suspicious.
     * @param suspiciousIPs Number of IP addresses flagged as suspicious.
     * @param riskLevel Overall security risk level.
     * @param firstLogTime Timestamp of the first log entry.
     * @param lastLogTime Timestamp of the last log entry.
     * @param mostTargetedUser Username with the highest failed login attempts.
     * @param maxFailedAttempts Highest number of failed login attempts by a user.
     * @param mostSuspiciousIP IP address with the highest failed login attempts.
     * @param maxIPFailedAttempts Highest number of failed login attempts from a single IP.
     * @param scanStatus Status of the security scan.
     * @param generatedBy Name and version of the application that generated the report.
     */
    public void generateReport(
            int totalLogs,
            int successfulLogins,
            int failedLogins,
            int uniqueUsers,
            int uniqueIPs,
            int suspiciousUsers,
            int suspiciousIPs,
            String riskLevel,
            String firstLogTime,
            String lastLogTime,
            String mostTargetedUser,
            int maxFailedAttempts,
            String mostSuspiciousIP,
            int maxIPFailedAttempts,
            String scanStatus,
            String generatedBy) {

        System.out.println("========================================");
        System.out.println("      CyberShield Security Report");
        System.out.println("========================================");

        System.out.println("Total Logs         : " + totalLogs);
        System.out.println("Successful Logins  : " + successfulLogins);
        System.out.println("Failed Logins      : " + failedLogins);
        System.out.println("Unique Users       : " + uniqueUsers);
        System.out.println("Unique IPs         : " + uniqueIPs);

        System.out.println("========================================");
        System.out.println();

        System.out.println("Log Timeline");
        System.out.println("------------");
        System.out.println("First Log : " + firstLogTime);
        System.out.println("Last Log  : " + lastLogTime);
        System.out.println();

        System.out.println("Event Distribution");
        System.out.println("------------------");
        System.out.println("LOGIN_SUCCESS : " + successfulLogins);
        System.out.println("LOGIN_FAILED  : " + failedLogins);
        System.out.println();

        System.out.println("Threat Summary");
        System.out.println("--------------");
        System.out.println("Suspicious Users : " + suspiciousUsers);
        System.out.println("Suspicious IPs   : " + suspiciousIPs);
        System.out.println();

        System.out.println("Most Targeted User : " + mostTargetedUser);
        System.out.println("Failed Attempts    : " + maxFailedAttempts);
        System.out.println();

        System.out.println("Most Suspicious IP : " + mostSuspiciousIP);
        System.out.println("Failed Attempts    : " + maxIPFailedAttempts);

        System.out.println("========================================");
        System.out.println();

        System.out.println("Overall Risk Level : " + riskLevel);
        System.out.println("========================================");

        System.out.println();
        System.out.println("Scan Status : " + scanStatus);
        System.out.println("Generated By: " + generatedBy);
        System.out.println("========================================");

    }

}
